public class Constants {
    
    public static final Integer DEFAULT_ROWS = 5;
    public static final String SELECT_ONE  = label.Select_One;
        public static final String INVENTORY_LEVEL_LOW  =  label.Inventory_Level_Low;
        public static final List<Schema.PicklistEntry> PRODUCT_FAMILY  = Product2.Family.getDescribe().getPickListValues();
    
        public static final string DRAFT_ORDER_STATUS  = 'Draft';
    
        public static final string ACTIVATED_ORDER_STATUS  = 'Activated';
        public static final string INVENTORY_ANNOUNCEMENTS  = 'Inventory Announcements';
        public static final string ERROR_MESSAGE = 'An error has occurred, please take a screenshot with the URL and send it to IT.';
    public static final string STANDARD_PRICEBOOK_ID  = '01s7F000002ljdMQAQ';
        

}