public class Doc_HubEquifaxCreditValidation {
 /*
  * 
  * 
1. EquifaxCreditValidation - 92%
2. BC_ConsumerCreditReviewQueueable - 100%
3. BC_ConsumerCreditReview - 95%

1. HubServiceScheduleConfig - Run  - 100%
2. HubServiceSchedulable - 100%
3. HubEquifaxServiceBatch - 100%
4. PrepareHubEquifaxServiceRequest - 90%
5. HubEquifaxServiceQueueable - 100%
6. ParseHubEquifaxServiceResponse - 100%

HubServiceSchedulableTest
HubEquifaxTestMock

*/
}